#[tomlConfig]
version = "0.0.3"   # версия конфигурационного файла
# 0.0.1 - начальная версия
# 0.0.2 - несколько портов, насколько устройств (нод) на порту
# 0.0.3 - добавлены порты по TCP на порту
upport_tcp = 45502  # порт для системы верхего уровня
local_port = 17000
count_tty_serial = 0        # должно быть реальное значение каналов
count_tcp_serial = 1

[[tcp_serial]]
# с версии 0.17 указыавем полный путь к устройству
    mode = "TCP"        # or UDP - пока UDP не рассматриваем
    ip = "192.168.1.128"
#    ip = "127.0.0.1"     # при отладке на симуляторе - localhost
#    ip = "192.168.0.4"    # при отладке на симуляторе Modbus Slave через внешний IP
    port = 502          # port used
    time_loop = 3000
    count_node = 3       # количество устройств на порту
# описание nede? как и в tty_serial
# input registers – ИЭ05-1
    [[tcp_serial.set_node]]
        enable = true          # работает или нет
        address_id = 1         # адрес устройства на шине (1..247)
        command = 3            # команда запроса – запрос INPUT регитстров из устройства
        address_data = 3       # адрес данных в устройстве
        data_length = 4        # длинна запрашиваемых данных только 30004-7
        index_up = 6          # индекс на общей карте параметров
# input registers – ИЭ05-2
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 1          # адрес устройства на шине (1..247)
        command = 3             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 7        # адрес данных в устройстве
        data_length = 4         # длинна запрашиваемых данных только
        index_up = 10          # индекс на общей карте параметров
# input registers – ИЭ05-3
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 1          # адрес устройства на шине (1..247)
        command = 3             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 13        # адрес данных в устройстве
        data_length = 1         # длинна запрашиваемых данных только
        index_up = 14           # индекс на общей карте параметров


[[tcp_serial]]


